### PR TITLE
feat: expose flag to disable strict name checking in service registration

### LINKED ISSUE #1046: Add method to disable strict service name checking.
There's no way to specify that invalid names should be allowed when registering a service.  I'm trying to register a service of "_oculusal_sp._tcp.local." (which is what the oculus quest 2 uses for airlinking), but I get an BadTypeInNameException error.  For now I have a monkey-fix workaround of
```python
zeroconf.service_type_name.__kwdefaults__['strict'] = False
```

### PR DESCRIPTION
**Pull request by azogue**
closes #1046

### CODE REVIEW

**Comment by garethsb** [comment]
👍 Thanks for this, hope it can be merged soon. For working with existing protocols that use strictly-invalid service types, we have had to adjust our monkeypatch several times. 🐒😄

**Comment by garethsb** [comment]
@bdraco thanks for considering this PR when you have time

**Comment by bdraco** [comment]
The following can be called directly so they should get a simple test to make sure disabling works when called directly:

- bound `async_check_service`

These are exposed at the top level for backwards compat which we likely need to maintain forever so they should get a test as well:
- `service_type_name`
- `instance_name_from_service_info`
https://github.com/python-zeroconf/python-zeroconf/blob/8a9dc0bf41bfb350e82aaf07a432bf414f6bce87/src/zeroconf/__init__.py#L69
https://github.com/python-zeroconf/python-zeroconf/blob/8a9dc0bf41bfb350e82aaf07a432bf414f6bce87/src/zeroconf/__init__.py#L62

**Comment by azogue** [comment]
> The following can be called directly so they should get a simple test to make sure disabling works when called directly:
> 
> * bound `async_check_service`
> 
> These are exposed at the top level for backwards compat which we likely need to maintain forever so they should get a test as well:
> 
> * `service_type_name`
> * `instance_name_from_service_info`
>   https://github.com/python-zeroconf/python-zeroconf/blob/8a9dc0bf41bfb350e82aaf07a432bf414f6bce87/src/zeroconf/__init__.py#L69
>   
>   https://github.com/python-zeroconf/python-zeroconf/blob/8a9dc0bf41bfb350e82aaf07a432bf414f6bce87/src/zeroconf/__init__.py#L62

Hi @bdraco, please take a look now 👍

I was not sure where to put those calls:
- Added explicit call to `Zeroconf.async_check_service` in test_asyncio.py
- Added a new unit test in utils/test_name.py to check explicit calls to `service_type_name` and  `instance_name_from_service_info`

Also, I re-pushed the branch to rename the old 2 commits (just de-capitalized the titles, after seeing a CI fail with the GAs 😅)

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
Tested on production. Didn't find any issues

Thanks @azogue

**Pull request merged**
